import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import ActionBadge, { SEVERITY } from "../components/ActionBadge";
import Disclaimer from "../components/Disclaimer";
import Spinner from "../components/Spinner";
import { api } from "../lib/api";
import useAnalysis from "../lib/useAnalysis";

const fmt = (s) => new Date(s + (s.endsWith("Z") || s.includes("+") ? "" : "Z")).toLocaleString("fr-FR", { dateStyle: "medium", timeStyle: "short" });

// Past analyses, opened read-only (MiFID II Art. 25(6): clients can retrieve earlier suitability statements)
function History({ refreshKey }) {
  const [items, setItems] = useState([]);
  const [open, setOpen] = useState(null);

  useEffect(() => {
    api("/recommendations").then(setItems).catch(() => setItems([]));
  }, [refreshKey]);

  const view = (id) => api(`/recommendations/${id}`).then(setOpen).catch(() => setOpen(null));
  if (items.length === 0) return null;

  return (
    <section className="card">
      <h2 className="font-semibold">History</h2>
      <ul className="mt-3 divide-y divide-slate-100">
        {items.map((h) => (
          <li key={h.id} className="flex items-center justify-between gap-3 py-2 text-sm">
            <span>{fmt(h.created_at)}<span className="text-slate-500"> · {h.mode === "demo" ? "demo mode" : h.mode}{h.outdated && " · outdated"}</span></span>
            <button onClick={() => view(h.id)} className="font-semibold text-ink hover:underline">View</button>
          </li>
        ))}
      </ul>
      {open && (
        <div className="mt-4 space-y-3 rounded-xl bg-slate-50 p-4">
          <div className="flex items-center justify-between text-xs text-slate-500">
            <span>Analysis of {fmt(open.created_at)} (read-only)</span>
            <button onClick={() => setOpen(null)} className="font-semibold hover:text-ink">Close</button>
          </div>
          <p className="text-sm leading-relaxed">{open.analysis.summary}</p>
          <ul className="space-y-2 text-sm">
            {open.analysis.recommendations.map((r, i) => (
              <li key={i}><span className="font-medium">{r.ticker}</span> · {r.title}<div className="text-xs text-slate-500">{r.rationale}</div></li>
            ))}
          </ul>
          <Disclaimer text={open.disclaimer} />
        </div>
      )}
    </section>
  );
}

export default function Recommendations() {
  const { analysis, generating, error, generate } = useAnalysis();
  const a = analysis?.analysis;

  return (
    <div className="space-y-5">
      <div className="flex items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Your analysis</h1>
          <p className="text-sm text-slate-500">
            {analysis ? (analysis.source === "demo" ? "Demo mode — rule-based, set MISTRAL_API_KEY for AI analysis" : "Generated by Mistral AI") : "Personalised to your profile and holdings"}
          </p>
        </div>
        <button onClick={generate} disabled={generating} className="btn-primary shrink-0 px-3 py-2 text-xs">
          {generating ? "Analysing…" : analysis ? "Regenerate" : "Analyse"}
        </button>
      </div>

      <Disclaimer text={analysis?.disclaimer} />
      {analysis?.outdated && (
        <p role="alert" className="rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-800 ring-1 ring-amber-200">Your profile changed. Refresh this analysis before acting on it.</p>
      )}
      {error && (
        <p className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">
          {error} {error.includes("holding") && <Link to="/portfolio" className="font-semibold underline">Add holdings</Link>}
        </p>
      )}

      {analysis === undefined || generating ? (
        <div className="card"><Spinner label={generating ? "Mistral is analysing your portfolio…" : "Loading…"} /></div>
      ) : !a ? (
        <div className="card text-center text-slate-600">
          No analysis yet. Click <strong>Analyse</strong> to get your personalised recommendations.
        </div>
      ) : (
        <>
          <section className="card">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Summary</h2>
            <p className="mt-2 leading-relaxed">{a.summary}</p>
          </section>

          <section className={`rounded-2xl p-5 ring-1 ${SEVERITY[a.risk_flag.severity]}`}>
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide">
              <span>⚠ Risk flag</span><span className="opacity-60">· {a.risk_flag.severity}</span>
            </div>
            <h3 className="mt-1 font-semibold">{a.risk_flag.title}</h3>
            <p className="mt-1 text-sm leading-relaxed">{a.risk_flag.detail}</p>
          </section>

          <section className="space-y-3">
            <h2 className="font-semibold">Recommendations</h2>
            {a.recommendations.map((r, i) => (
              <article key={i} className="card">
                <div className="flex items-center gap-2">
                  <span className="grid size-6 place-items-center rounded-full bg-slate-100 text-xs font-bold">{i + 1}</span>
                  {!analysis.outdated && <ActionBadge action={r.action} />}
                  <span className="text-sm font-medium text-slate-500">{r.ticker}</span>
                </div>
                <h3 className="mt-3 font-semibold">{r.title}</h3>
                <p className="mt-1 text-sm leading-relaxed text-slate-600">{r.rationale}</p>
              </article>
            ))}
          </section>

          <section className="card">
            <h2 className="font-semibold">Rebalancing suggestion</h2>
            <p className="mt-2 text-sm leading-relaxed text-slate-600">{a.rebalancing.summary}</p>
            <ul className="mt-4 space-y-3">
              {a.rebalancing.target_allocation.map((t, i) => (
                <li key={i}>
                  <div className="flex justify-between text-sm">
                    <span>{t.label}</span>
                    <span className="font-semibold tabular-nums">{Number(t.percent).toFixed(0)}%</span>
                  </div>
                  <div className="mt-1 h-2 rounded-full bg-slate-100">
                    <div className="h-full rounded-full bg-brand" style={{ width: `${Math.min(100, Number(t.percent) || 0)}%` }} />
                  </div>
                </li>
              ))}
            </ul>
          </section>

          <Disclaimer text={analysis.disclaimer} />
        </>
      )}

      <History refreshKey={analysis?.id} />
    </div>
  );
}
