import { Link } from "react-router-dom";
import ActionBadge, { SEVERITY } from "../components/ActionBadge";
import Disclaimer from "../components/Disclaimer";
import Spinner from "../components/Spinner";
import useAnalysis from "../lib/useAnalysis";

export default function Recommendations() {
  const { analysis, generating, error, generate } = useAnalysis();
  const a = analysis?.analysis;

  return (
    <div className="space-y-5">
      <div className="flex items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Your analysis</h1>
          <p className="text-sm text-slate-500">
            {analysis ? (analysis.source === "demo" ? "Demo mode — rule-based, set MISTRAL_API_KEY for AI analysis" : "Generated by Mistral AI") : "Personalised to your profile and holdings"}
          </p>
        </div>
        <button onClick={generate} disabled={generating} className="btn-primary shrink-0 px-3 py-2 text-xs">
          {generating ? "Analysing…" : analysis ? "Regenerate" : "Analyse"}
        </button>
      </div>

      <Disclaimer text={analysis?.disclaimer} />
      {error && (
        <p className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">
          {error} {error.includes("holding") && <Link to="/portfolio" className="font-semibold underline">Add holdings</Link>}
        </p>
      )}

      {analysis === undefined || generating ? (
        <div className="card"><Spinner label={generating ? "Mistral is analysing your portfolio…" : "Loading…"} /></div>
      ) : !a ? (
        <div className="card text-center text-slate-600">
          No analysis yet. Click <strong>Analyse</strong> to get your personalised recommendations.
        </div>
      ) : (
        <>
          <section className="card">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Summary</h2>
            <p className="mt-2 leading-relaxed">{a.summary}</p>
          </section>

          <section className={`rounded-2xl p-5 ring-1 ${SEVERITY[a.risk_flag.severity]}`}>
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide">
              <span>⚠ Risk flag</span><span className="opacity-60">· {a.risk_flag.severity}</span>
            </div>
            <h3 className="mt-1 font-semibold">{a.risk_flag.title}</h3>
            <p className="mt-1 text-sm leading-relaxed">{a.risk_flag.detail}</p>
          </section>

          <section className="space-y-3">
            <h2 className="font-semibold">Recommendations</h2>
            {a.recommendations.map((r, i) => (
              <article key={i} className="card">
                <div className="flex items-center gap-2">
                  <span className="grid size-6 place-items-center rounded-full bg-slate-100 text-xs font-bold">{i + 1}</span>
                  <ActionBadge action={r.action} />
                  <span className="text-sm font-medium text-slate-500">{r.ticker}</span>
                </div>
                <h3 className="mt-3 font-semibold">{r.title}</h3>
                <p className="mt-1 text-sm leading-relaxed text-slate-600">{r.rationale}</p>
              </article>
            ))}
          </section>

          <section className="card">
            <h2 className="font-semibold">Rebalancing suggestion</h2>
            <p className="mt-2 text-sm leading-relaxed text-slate-600">{a.rebalancing.summary}</p>
            <ul className="mt-4 space-y-3">
              {a.rebalancing.target_allocation.map((t, i) => (
                <li key={i}>
                  <div className="flex justify-between text-sm">
                    <span>{t.label}</span>
                    <span className="font-semibold tabular-nums">{Number(t.percent).toFixed(0)}%</span>
                  </div>
                  <div className="mt-1 h-2 rounded-full bg-slate-100">
                    <div className="h-full rounded-full bg-brand" style={{ width: `${Math.min(100, Number(t.percent) || 0)}%` }} />
                  </div>
                </li>
              ))}
            </ul>
          </section>

          <Disclaimer text={analysis.disclaimer} />
        </>
      )}
    </div>
  );
}
